name: Build and release GNOME shell extension

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install blueprint-compiler
        run: sudo apt-get install libgtk-4-dev libadwaita-1-dev blueprint-compiler gobject-introspection

      - name: Install packages
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Build & pack .zip
        run: make pack

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gdeej.zip
